### ISSUE TITLE
ban or not ban

### ISSUE THREAD

**Issue by Muciyee** [xAranaktu/FIFA-23-CM-Cheat-Table#19]
I can get banned for using CT in career mode? Am I right?
If yes, how can I bypass it and don't get ban for using it in career mode?

**Comment by xAranaktu** [comment]
Yes, you can. You can't bypass it.

**Comment by xAranaktu** [comment]
Even if it's single player, even if you turn off internet. For sure this will make you a little bit safer, but it won't guarantee you in 100% that you won't be ever banned. Look, if EA will want to ban people for using Live Editor they will do it. I don't know what's in their heads, but definitely they have tools and resources to ban every single Live Editor user.

**Comment by Muciyee** [comment]
Thank you for answer. And sorry my bad english, lifted mean ban was deleted?
And banning they only account like all others, right? I can use another account online after that I mean

**Comment by xAranaktu** [comment]
lifted mean unbanned. Ban is per account, you can create new account and buy the game again to continue playing. I don't know what mistake that guy made, probably he was accidentally banned. I doubt it was because of the live editor. EA won't tell you why they ban you exactly, you will just receive email that you account is suspend because of violating rules and that's all. You never get detailed explanation on what you did wrong.

**Comment by Muciyee** [comment]
Okay, got you. Thank you for answers
